/**
 * Daftar event audit — BRD/SRS v1.1 §4.5.
 * Nilai konstanta dipakai apa adanya sebagai kolom `action`.
 */
export const AuditAction = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  LOGOUT: 'LOGOUT',

  MFA_CHALLENGE_SENT: 'MFA_CHALLENGE_SENT',
  MFA_SUCCESS: 'MFA_SUCCESS',
  MFA_FAILED: 'MFA_FAILED',

  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',

  CREATE_REPORT: 'CREATE_REPORT',
  UPDATE_REPORT: 'UPDATE_REPORT',
  ARCHIVE_REPORT: 'ARCHIVE_REPORT',
  STATUS_CHANGE: 'STATUS_CHANGE',

  VIEW_EVIDENCE: 'VIEW_EVIDENCE',
  VIEW_PROOF: 'VIEW_PROOF',
  DOWNLOAD_PDF: 'DOWNLOAD_PDF',

  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',
  PAYMENT_RECONCILE: 'PAYMENT_RECONCILE',

  PRICE_CONFIG_CHANGE: 'PRICE_CONFIG_CHANGE',
  TAX_CONFIG_CHANGE: 'TAX_CONFIG_CHANGE',

  LEGAL_CREATE: 'LEGAL_CREATE',
  LEGAL_UPDATE: 'LEGAL_UPDATE',
  LEGAL_ARCHIVE: 'LEGAL_ARCHIVE',

  POLICY_CREATE: 'POLICY_CREATE',
  POLICY_UPDATE: 'POLICY_UPDATE',
  POLICY_ARCHIVE: 'POLICY_ARCHIVE',

  USER_UPDATE: 'USER_UPDATE',
  ROLE_CHANGE: 'ROLE_CHANGE',
  PERMISSION_CHANGE: 'PERMISSION_CHANGE',

  REVIEW_APPROVE: 'REVIEW_APPROVE',
  REVIEW_REJECT: 'REVIEW_REJECT',
  REVIEW_REQUEST_REVISION: 'REVIEW_REQUEST_REVISION',

  EXTERNAL_SUBMISSION: 'EXTERNAL_SUBMISSION',

  PROOF_UPLOAD: 'PROOF_UPLOAD',
  PROOF_UPDATE: 'PROOF_UPDATE',
  PROOF_VOID: 'PROOF_VOID',

  PDF_GENERATION: 'PDF_GENERATION',
  NOTIFICATION_RETRY: 'NOTIFICATION_RETRY',
  DATA_EXPORT: 'DATA_EXPORT',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',

  /** Upaya akses objek milik orang lain (AC-07). */
  ACCESS_DENIED: 'ACCESS_DENIED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];
